<?php
/****
 * 通过trait 实现多继承
 * DateTime: 2021/9/7 1:26 下午
 * ClassName: Base
 */



class Base{
    public function test()
    {
        echo 'base_test'."\n\n";
    }
}

trait traitA{
    public function testA()
    {
        echo "test trait A \n\n";
    }
}

trait traitB{

    public function testB()
    {
        echo "test trait B \n\n";
    }
}

class Handle
{
    use traitB;
    use traitA;
    public function test1()
    {
        //只能通过静态的方式调用
        self::testA(); // TODO: Change the autogenerated stub
        self::testB();
    }
}

(new Handle())->test1();