FROM nginx
RUN echo '这是一个本地构建的nginx镜像' > /usr/share/nginx/html/index.html

#这是一个Dockerfile文件（注意文件名必须叫Dockerfile）
#构建： docker build -t nginx1:test1 .   在当前目录执行
#执行后 运行docker images 发现新出来一个nginx1 镜像 tag为test1
#   REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
#   nginx1                  test1               504b9a68c04c        7 seconds ago       132MB




